version: '3.7'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
     - .:/usr/src/rest
    ports:
     - 8000:8000
    env_file:
     - .env.dev
  db:
    env_file:
     - .env.dev
    image: postgres:13.0-alpine
    volumes:
     - postgres_data:/var/lib/postgresql/data/
    environment:
     - POSTGRES_USER=${SQL_USER}
     - POSTGRES_PASSWORD=${SQL_PASSWORD}
volumes:
  postgres_data:
