# Generated by Django 3.1.5 on 2021-01-24 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='comments_count',
            new_name='message_count',
        ),
    ]
