# Generated by Django 3.1.5 on 2021-01-25 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20210124_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'subcategories'},
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='messages_count',
            new_name='message_count',
        ),
    ]
